/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type TrackReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "track";
};

export type LiveStatus = {
  _type: "liveStatus";
  state: "onTime" | "delayed" | "moved" | "cancelled";
  delayMinutes?: number;
  movedToTrack?: TrackReference;
  note?: string;
};

export type Link = {
  _type: "link";
  label: string;
  href: string;
};

export type SpeakerReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "speaker";
};

export type Session = {
  _id: string;
  _type: "session";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  type: "talk" | "keynote" | "workshop" | "panel" | "break" | "registration";
  abstract?: string;
  speakers?: Array<
    {
      _key: string;
    } & SpeakerReference
  >;
  language?: "es" | "en";
  level?: "intro" | "intermediate" | "advanced";
  track: TrackReference;
  startsAt: string;
  durationMinutes: number;
  capacity?: number;
  signupUrl?: string;
  recorded?: boolean;
  captioned?: boolean;
  liveStatus?: LiveStatus;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Speaker = {
  _id: string;
  _type: "speaker";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  jobTitle?: string;
  organisation?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  links?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Track = {
  _id: string;
  _type: "track";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  shortName?: string;
  order: number;
  capacity?: number;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  tagline?: string;
  startDate: string;
  endDate: string;
  timezone: string;
  venueName?: string;
  city?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | TrackReference
  | LiveStatus
  | Link
  | SpeakerReference
  | Session
  | Slug
  | SanityImageAssetReference
  | Speaker
  | SanityImageCrop
  | SanityImageHotspot
  | Track
  | Event
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/lib/sanity/queries.ts
// Variable: programmeQuery
// Query: {  "event": *[_type == "event" && !(_id in path("drafts.**"))][0]{    name,    tagline,    startDate,    endDate,    timezone,    venueName,    city  },  "rooms": *[_type == "track" && !(_id in path("drafts.**"))] | order(order asc){    "id": _id,    name,    shortName,    "slug": slug.current,    order,    capacity  },  "sessions": *[    _type == "session"    && !(_id in path("drafts.**"))    && defined(startsAt)    && defined(durationMinutes)    && defined(track._ref)  ] | order(startsAt asc){    "id": _id,    "slug": slug.current,    title,    type,    language,    level,    startsAt,    durationMinutes,    recorded,    captioned,    "roomId": track._ref,    "speakers": speakers[]->{      "id": _id,      name,      "slug": slug.current,      jobTitle,      organisation    },    "status": liveStatus{      state,      delayMinutes,      note,      "movedToRoomId": movedToTrack._ref    }  }}
export type ProgrammeQueryResult = {
  event: {
    name: string;
    tagline: string | null;
    startDate: string;
    endDate: string;
    timezone: string;
    venueName: string | null;
    city: string | null;
  } | null;
  rooms: Array<{
    id: string;
    name: string;
    shortName: string | null;
    slug: string;
    order: number;
    capacity: number | null;
  }>;
  sessions: Array<{
    id: string;
    slug: string;
    title: string;
    type: "break" | "keynote" | "panel" | "registration" | "talk" | "workshop";
    language: "en" | "es" | null;
    level: "advanced" | "intermediate" | "intro" | null;
    startsAt: string;
    durationMinutes: number;
    recorded: boolean | null;
    captioned: boolean | null;
    roomId: string;
    speakers: Array<{
      id: string;
      name: string;
      slug: string;
      jobTitle: string | null;
      organisation: string | null;
    }> | null;
    status: {
      state: "cancelled" | "delayed" | "moved" | "onTime";
      delayMinutes: number | null;
      note: string | null;
      movedToRoomId: string | null;
    } | null;
  }>;
};

// Source: src/lib/sanity/queries.ts
// Variable: sessionQuery
// Query: {  "event": *[_type == "event" && !(_id in path("drafts.**"))][0]{    name,    tagline,    startDate,    endDate,    timezone,    venueName,    city  },  "rooms": *[_type == "track" && !(_id in path("drafts.**"))] | order(order asc){    "id": _id,    name,    shortName,    "slug": slug.current,    order,    capacity  },  "session": *[    _type == "session"    && !(_id in path("drafts.**"))    && slug.current == $slug  ][0]{    "id": _id,    "slug": slug.current,    title,    type,    abstract,    language,    level,    startsAt,    durationMinutes,    recorded,    captioned,    capacity,    signupUrl,    "roomId": track._ref,    "speakers": speakers[]->{      "id": _id,      name,      "slug": slug.current,      jobTitle,      organisation    },    "status": liveStatus{      state,      delayMinutes,      note,      "movedToRoomId": movedToTrack._ref    }  }}
export type SessionQueryResult = {
  event: {
    name: string;
    tagline: string | null;
    startDate: string;
    endDate: string;
    timezone: string;
    venueName: string | null;
    city: string | null;
  } | null;
  rooms: Array<{
    id: string;
    name: string;
    shortName: string | null;
    slug: string;
    order: number;
    capacity: number | null;
  }>;
  session: {
    id: string;
    slug: string;
    title: string;
    type: "break" | "keynote" | "panel" | "registration" | "talk" | "workshop";
    abstract: string | null;
    language: "en" | "es" | null;
    level: "advanced" | "intermediate" | "intro" | null;
    startsAt: string;
    durationMinutes: number;
    recorded: boolean | null;
    captioned: boolean | null;
    capacity: number | null;
    signupUrl: string | null;
    roomId: string;
    speakers: Array<{
      id: string;
      name: string;
      slug: string;
      jobTitle: string | null;
      organisation: string | null;
    }> | null;
    status: {
      state: "cancelled" | "delayed" | "moved" | "onTime";
      delayMinutes: number | null;
      note: string | null;
      movedToRoomId: string | null;
    } | null;
  } | null;
};

// Source: src/lib/sanity/queries.ts
// Variable: sessionSlugsQuery
// Query: *[_type == "session" && !(_id in path("drafts.**")) && defined(slug.current)].slug.current
export type SessionSlugsQueryResult = Array<string>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '{\n  "event": *[_type == "event" && !(_id in path("drafts.**"))][0]{\n    name,\n    tagline,\n    startDate,\n    endDate,\n    timezone,\n    venueName,\n    city\n  },\n  "rooms": *[_type == "track" && !(_id in path("drafts.**"))] | order(order asc){\n    "id": _id,\n    name,\n    shortName,\n    "slug": slug.current,\n    order,\n    capacity\n  },\n  "sessions": *[\n    _type == "session"\n    && !(_id in path("drafts.**"))\n    && defined(startsAt)\n    && defined(durationMinutes)\n    && defined(track._ref)\n  ] | order(startsAt asc){\n    "id": _id,\n    "slug": slug.current,\n    title,\n    type,\n    language,\n    level,\n    startsAt,\n    durationMinutes,\n    recorded,\n    captioned,\n    "roomId": track._ref,\n    "speakers": speakers[]->{\n      "id": _id,\n      name,\n      "slug": slug.current,\n      jobTitle,\n      organisation\n    },\n    "status": liveStatus{\n      state,\n      delayMinutes,\n      note,\n      "movedToRoomId": movedToTrack._ref\n    }\n  }\n}': ProgrammeQueryResult;
    '{\n  "event": *[_type == "event" && !(_id in path("drafts.**"))][0]{\n    name,\n    tagline,\n    startDate,\n    endDate,\n    timezone,\n    venueName,\n    city\n  },\n  "rooms": *[_type == "track" && !(_id in path("drafts.**"))] | order(order asc){\n    "id": _id,\n    name,\n    shortName,\n    "slug": slug.current,\n    order,\n    capacity\n  },\n  "session": *[\n    _type == "session"\n    && !(_id in path("drafts.**"))\n    && slug.current == $slug\n  ][0]{\n    "id": _id,\n    "slug": slug.current,\n    title,\n    type,\n    abstract,\n    language,\n    level,\n    startsAt,\n    durationMinutes,\n    recorded,\n    captioned,\n    capacity,\n    signupUrl,\n    "roomId": track._ref,\n    "speakers": speakers[]->{\n      "id": _id,\n      name,\n      "slug": slug.current,\n      jobTitle,\n      organisation\n    },\n    "status": liveStatus{\n      state,\n      delayMinutes,\n      note,\n      "movedToRoomId": movedToTrack._ref\n    }\n  }\n}': SessionQueryResult;
    '\n  *[_type == "session" && !(_id in path("drafts.**")) && defined(slug.current)].slug.current\n': SessionSlugsQueryResult;
  }
}
